# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_DataInfo(QMainWindow):

    def __init__(self, dataInformation):
        super(Ui_DataInfo, self).__init__()
        self.dataInformation = dataInformation
        self.setupUi()
        self.load_DataInfo()

    def setupUi(self):
        self.setObjectName("DataInfo")
        self.resize(476, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        # Create the QScrollArea
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 451, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        # Create a widget to contain the text browser
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # Set the vertical layout for the scroll area contents
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        # Create the QTextBrowser
        self.textB_data = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textB_data.setObjectName("textB_data")
        self.verticalLayout.addWidget(self.textB_data)

        # Set the widget for the scroll area
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, DataInfo):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("DataInfo", "Data Information"))

    def load_DataInfo(self):
        self.textB_data.setText(self.dataInformation)